DROP TABLE IF EXISTS Missions;
DROP TABLE IF EXISTS Company_success_rate;
DROP TABLE IF EXISTS Location_success_rate;
DROP TABLE IF EXISTS Rocket_success_rate;
DROP TABLE IF EXISTS Produces;
DROP TABLE IF EXISTS Rockets;
DROP TABLE IF EXISTS Companies;
DROP TABLE IF EXISTS Locations;